#+TITLE: Notes on: Analyzing memory: the formation, retention, and measurement of memory by Chechile, R. A. (2018)
#+Time-stamp: <2021-05-28 16:06:14 boxx>

- source :: cite:chechile-2018-analy

* TODO Summary

* TODO Comments

* TODO Topics

** Building Memory Representations

#+begin_quote
If any one faculty of our nature may be called more wonderful than the rest, I do think it is memory. There seems something speakingly incomprehensible in the powers, the failures, the inequalities of memory, than in any other of our intelligences. The memory is sometimes so retentive, so serviceable, so obedient; at others, so bewildered and so weak; and at others again, so tyrannic, so beyond control! We are, to be sure, a miracle every way; but our powers of recollecting and of forgetting do seem peculiarly past finding out. (Jane Austen, 1814, /Mansfield Park/, p. 141)
#+end_quote

This volume is my attempt to begin the description of how human memory works, how it is organized, and how it dynamically changes. The broad architecture of the approach is developed from a number of perspectives or levels of analysis. Each framework contributes to the overall picture about memory. But before describing the organization of part I of the book, it is helpful to first clarify what is meant by levles of analysis and to discuss the role of modeling in memory research.

*** Levels of Scientific Inquiry

Unlike some branches of mathematics that seem to built up from a set of initial axioms or foundational assumptions, science operates simultaneously at many different levels, and usually there is minimal linkage across levels. Elementary particle physics is the lowest level of scientific description. A proton is not an elementary particle because it has the internal structure of two (2) up quarks and one (1) down quark. A neutron is also not an elementary particle because it is composed of two (2) down quarks and one (1) up quark. The quarks are elementary (*irreducible*) components of matter *(!)*. The nucleus of an element is a complex structure of protons and neutrons, yet the fields of particle physics and nuclear physics are not required to describe properties of chemical interactions. The only pertinent fact about the nucleus of an atom that a chemist needs to know is the total number of protons because a neutral atom has the same number of electrons. Chemistry is the study of these electrons and the interactions of the electrons with the electrons from other atoms. Chemistry does not have to be concerned with the complexities of the atomic nucleus in order to develop a sophisticated and valuable science. Similarly, a single biological cell is a complex system that is made up of many molecules, yet properties of the cell can be described without knowing its detailed chemical structure. The biologist can also describe how a collection of cells functions without reducing the description to a more elementary level. Moreover, a whole collection of people can be treated in sociology and economics as a system. Each scientific field from elementary particles to a society can be treated as a system or domain with discernible properties. Different scientist systems typically have their own language, intellectual constructs, and measurement instruments. It is pointless and foolhardy to attempt to understand a social phenomenon like /out-group discrimination/ in terms of particle physics or chemistry.

Memory can be examined at several different levels. For the most part, memory will be discussed in terms of the language of cognitive psychology. Topics such as /false memory/ or the /misinformation effect/ make little sense at the cellular level or at the neuranatomical level. Similarly, ascertaining the proportion of stored memories that are retrievable within a specific time limit can be treated at the cognitive level, but it would not be a suitable question at the physiological level. But some types of learning are elementary and are shared across animal species. For these types of memories, it is best to avoid a higher-level cognitive framework and to use instead simpler, mechanical models, if possible. Animal studies also enable experimental methods and measurements that are not ethically possible with humans. These elementary types of memories include /habituation/ and /sensitization/. The studies at the biological level introduce some important general principles that apply to more complex memory processes.

Many memory researchers have divided memory into different systems that are argued to be separate, autonomous entities much like the liver is different from the lungs. For example, working memory, long-term memory, procedural memory, semantic memory, and implicit memory have been hypothesized to be distinctly different systems that have different neurological foundations. The subdivision of memory has the practical value of allowing researchers to develop experimental evidence and theory within a more narrow context without the burden of accounting for how each type of memory relates to other types of memory. Narrowing the topic domain is a standard method in science. This sense of the phrase /memory systems/ is quite different from what is meant in the current book by the phrase a /system-level analysis/. Although there are different types of memories, the whole of memory is the focus of this book. In fact, a case will be made later that implicit memory can sometimes arise from the loss of information that was once explicitly stored *(!)*; thus, implicit memory is *not* a neurologically autonomous system. Consequently the system-level description of memory uses fundamental information-processing constructs rather than attempting to ground the description in a reductive fashion to biological and chemical mechanisms. Nonetheless, the systems-level theory must account for the behavioral phenomena, and it should be consistent with the known relevant facts obtained from biological studies.

*** Mathematical Models and the Study of Memory
