#+TITLE: Notes on: Perceptual learning: how experience shapes visual perception by Dosher, B., & Lu, Z. (2020)
#+Time-stamp: <2021-05-28 18:44:17 boxx>

- source :: cite:dosher-2020-percep-learn

* TODO Summary

* TODO Comments

* TODO Topics

** Principles of Perceptual Learning

Experience plays a fundamental role in perception. The importance of domain-specific training to the development of perceptual expertise is immense, but while in principle the plasticity underlying such changes may alter the responses of the visual system at the earliest levels, overall system stability must also be taken into account. In this chapter, we present a synthetic framework of perceptual learning that balances plasticity and stability alongside a number of other dipoles: signal and noise, readout and encoding, and top-down as well as stimulus-driven factors. *Our thesis is that reweighting, or changing the readout of sensory information, is the most likely candidate mechanism for optimizing learning across these many dimensions*.

*** The Importance of Experience and Learning in Perception

*Human perception is a necessary gateway to experience*. It is integral to learning about our physical surroundings, discovering our place within a wider environment, and ultimately the planning and execution of purposeful behavior. Perception is also something we take for granted. Consider an everyday stroll through a street market. As you walked, you would encounter an active and varied environment, remarkable in its complexity, which nevertheless seems to cohere into a whole. The shoppers passing by, the rows of fruits and vegetables, and the sunlight coming from above the rafters - all this visual information would be accessible to you, along with input from other modalities: the sounds of people talking, the scents of the cut fruit, the feel of the breeze, perhaps even the taste of your cup of coffee. Registering any of these perceptions may seem to require little conscious effort, yet making sense of such a welter of stimuli in fact draws on a network of immensely sophisticated cognitive processes. Successful processing of perceptual input is critical to our lives, and /how we get better at/ that processing will be the subject of this book.

We all know that some activities seem to rely more on advanced forms of perceptual analysis than others do. Anyone who has knitted a sweater or played a video game has made use of high-level visual and cognitive functions - functions that are tuned to our sensory machinery and that have developed over a lifetime of experience. In this sense, we are all perceptual experts, but we also know that many activities - not only knitting and gaming but also playing music or learning to detect letters in visual noise - almost always improve with training or practice. Major league baseball players, expert billiard players, and expert pilots are all better able to scan and process visual scenes than amateurs are. Although natural variance in ability is an important factor, expertise in sports or games will almost always require thousands of hours of practice and exposure to train specific skills. Baseball players are likely to be especially sensitive to motion cues; expert video gamers are often able to rapidly detect elements in their visual periphery; and avid bird-watchers are especially attuned to extracting texture from camouflage. In all these domains, perceptual training is a primary avenue toward expert levels of performance.

This turns out to be true not only for advanced tasks but also for simple ones. By the time we are adults, we can see a few photons of light energy in the dark and hear a sound that displaces the cochlear membrane of the ear by the diameter of a hydrogen atom. We can smell a drop of perfume in a large room, taste a single teaspoon of sugar dissolved in several gallons of water, and feel the lightest touch of a feather. Our senses are surprisingly acute. Yet, in all these examples, our sensitivity can be improved through training. *Extended practice can push these limits even further*.

In the laboratory, most research has focused on perceptual tasks that fall somewhere between very precise judgement of minimal stimuli and the intertwined complexity of natural expertise. Even so, this covers a wide range of tasks. It includes judgements of everything from low-level visual features to high-level natural objects, from training that last a few minutes to many thousands of trials over many days.

In almost all these cases, experience and practice have been shown to greatly enhance the quality of visual perception, and although perceptual learning is not entirely ubiquitous - it fails to occur in some cases and can be of modest magnitude in others - the phenomenon is so widespread that perception itself cannot be fully understood without it. *To understand perception also means to understand how it is modified by experience*.

*** Perceptual Learning in the Laboratory

The first reports of improved perceptual judgements date back to the late nineteenth century, but it wasn't until the 1960s that perceptual learning was identified as an important subject for scientific inquiry. The birth of the field is most associated with the work of psychologist Eleanor Gibson, whose 1969 book /Principles of Perceptual Learning and Development/ set out many of the fundamental phenomena still studied today.

In her seminal analysis, Gibson defined perceptual learning as a /relatively permanent and consistent change in the perception of a stimulus array, following practice with that array/. In the laboratory, this change has usually been measured by observing how practice improves the performance of a particular task. This almost always involves either detecting the presence of a stimulus or discriminating between two stimuli.

Performance, and thus learning, has been assessed in several ways. It can be measured as performance accuracy (and learning can be measured as an increase in accuracy), but it can also be measured as a threshold performance value of stimulus strength, or as the difference between stimuli at the threshold performance level (with learning in both cases seen as a decrease in threshold). In concrete terms, performance accuracy might be indexed by percentage correct or by a discriminability ~d'~; by the stimulus contrast required to achieve a threshold accuracy in some other judgement, such as orientation; or as a difference in the judged dimension, such as the orientation difference required to achieve the threshold accuracy level. Reduced response times are also sometimes used as an index of learning.

In real-world cases of expertise, perceptual stimuli and judgements are almost always multidimensional, and the performance context is complex. The tasks studied in the laboratory, however, usually involve relatively simple stimuli and judgements, with controlled training or practice protocols. Likewise, many laboratory tasks use coarser judgements and only sometimes focus on acute judgements such as the minimum perceivable stimulus. This is not to say that the task domain in the laboratory is overly narrow, simply that it is more simplified and constrained than in natural contexts. As we will see, tasks are often grouped according to their complexity, as low-, mid-, and high-level. Subjects may be asked to make judgements about basic visual features but also about natural objects. Most often, tasks involve judgements of mid-level visual features.

Although Gibson herself was interested in the role of perceptual learning in young children, whose visual systems are more *labile*, perceptual learning in the laboratory has most often been measured in adults, for whom the visual system is thought to be relatively stable (absent major injury). In fact, perceptual learning continues to occur throughout the individual's life span, from visual development to adulthood. It can even be used as a mitigating factor to stave off perceptual losses during aging and has also been studied as a route to remediation or rehabilitation in treatment regimines for clinical deficits.

One commonplace view that seemed to follow from observations of high plasticity during early development was that the visual system in adults was essentially stable (absent aging or damage). From this it was thought that perceptual learning, while measurable, would at best contribute marginally to performance. *This turns out not to be the case*. Perceptual learning in adults can have a significant impact on visual performance, even at the scale of laboratory practice. In some experiements, it has taken performance from slightly above chance to 90% correct or more. Similar learning effects have been seen in many tasks, from spatial-pattern and texture discrimination to motion discrimination. Although perceptual learning is more modest in some cases, the point remains that in adults it /can/ make very significant contributions to perceptual functionality. (This has implications beyond the study of learning as such, as it is important to know the stage of practice even when the goal of perceptual testing is not to understand learning but to characterize the visual system and its functions.)

Perceptual learning is a very broad phenomenon. It occurs in many sensory modalities and task domains - although it is visual learning that is of special interest in this book. Over the many thousands of experiments in which it has been studied, it has occurred far more often than not. Learning has been found in the detection or discrimination of visual patterns of many kinds: spatial patterns, complex objects, textures, faces, motion, and stereo depth. On the other hand, there are a few stimuli and tasks in which perceptual learning seems to have a relatively small effect or none at all. One such example is the discrimination between two patterns having different orientations around the horizontal or vertical in the fovea. (It has been suggested that the stability of performance relative to the cardinal axes results from the frequency with which such judgements are performed in everyday life.) Overall, however, initial task performance in almost any perceptual task is likely to be far from optimal and thus might be improved with practice or training.
