#+TITLE: Notes on: Natural language semantics by Gillon, B. S. (2019)
#+Time-stamp: <2021-06-07 20:31:52 boxx>

- source :: cite:gillon-2019-natur

* TODO Summary

The book's central question is the central question of natural language semantics: namely, how is one's understanding of a complex expression of natural language determined by one's understanding of the expressions making it up? This question is investigate with respect to English. And while English is the principal target language, other languages are occasionally discussed.

To answer the central question requires a characterization of how complex expressions are formed, on the one hand, and a way of characterizing one's understanding of the expressions, on the other. The characterization of how complex expressions of a natural language are formed is its syntax, and there are well-understood logical techniques to formalize natural language syntax. Characterizing how an expression is understood is another matter entirely. Traditionally, one speaks of what one understands when one understands an expression of natural language as the expression's meaning. But the notion of meaning is an elusive one and its nature continues to remain controversial. However, there is an ersatz for meaning, namely, set theoretic entities, which, when used as values assigned to expressions, provide at least a partial answer to the central question. The idea is to assign set theoretic entities to all expressions and to do so in such a way that the set theoretic entity assigned to a complex expression is determine by the set theoretic entities assigned to the simpler expressions making it up. The situation is analogous to the situation in logic. The notation of a logic has complex expressions that are made up of simpler expressions. Set theoretic entities are assigned to the expressions by assigning entities to the simpler expressions and using the formation rules, sometimes known as valuation rules, to state how an entity is assigned to the complex expressions made up from the simpler ones. It turns out that, in some cases, the techniques of logic can be applied to natural language expressions, off the shelf as it were; in many cases, however, the techniques of logic have to be adapted to the vagaries of natural language syntax. The subject matter of the book comprises, then on the one hand, the study of the patterns of the formation of complex expressions from simpler ones and the adoption or adaption from logic of rules, or valuations, whereby values are assigned to the complex expressions on the basis of the values assigned to the simpler ones.

* TODO Comments

This conception of natural language semantics is shared by many, if not most, approaches to the contemporary study of natural language semantics. However, the treatment in this book differs in several important ways from treatments found in other textbooks. Let me explain how.

The patterns in the expressions of a natural language semantics are rich and varied, and the theoretical approaches to them based on logic are numerous and demand a fair degree of logical knowledge. Students coming to the study of semantics, however, rarely have studied any logic and usually have studied no mathematics since secondary school. Most authors have therefore decided to teach one theoretical approach, their own, giving only a minimum explanation of the relevant logical techniques, and choosing only examples that suit the theory being taught. Thus, the facts presented are those that the theory handles best and the logic taught is just the logic used by that theory.

While such textbooks are often very good at introducing students to a particular theory of natural language semantics, they have, in my view, several drawbacks. This book aspires to enable readers with little or no postsecondary mathematical training to avoid these pitfalls. Rather than aiming to take readers on the shortest route possible to the point where they can read the literature of one particular theory, often losing all except those with an atecedent knack for mathematics, I take a longer route, which. though slower, takes diligent readers, regardless of mathematical or logical talent, to the point where they can read the literature in a variety of theories.

First, I concentrate on those ideas of logic essential to the various natural language semantic theories using logical techniques and take the time necessary to ensure that these ideas are understood and mastered. Second, I strive to ensure that readers have a good grasp of the range of patterns in English expressions and make clear to them which patterns have been successfully treated, which, though not treated, are amenable to a successful treatment, and which seem out of reach of any known treatment. Finally, most students who come to linguistics are students in the faculty of arts. They have little or no exposure to what empirical inquiry is, beyond what they may have gleaned from science classes in secondary school. In addition, many naive or outdated ideas about the nature of empirical inquiry circulate in linguistics. True, few, if any, linguists appeal to the behaviorist and verificationist ideas of scientific method, popular among linguists in the first half of the last century, but many appeal to the ideas that emerged in the middle of the last century, such as Karl Popper's falsificationism, and which, though serving as a healthy corrective to excesses of behaviorism and verificationism, themselves commit excesses that more recent work in the philosophy of science has corrected. These ideas, explained in the first chapter, are used and illustrated in subsequent chapters.

* TODO Topics

** The Study of Language before the Twentieth Century
