#+TITLE: Notes on: Commonsense reasoning: an event calculus based approach by Mueller, E. T. (2015)
#+Time-stamp: <2021-05-26 17:10:58 boxx>

- source :: cite:mueller-2015-common

* TODO Summary

This book is concerned with understanding and describing commonsense reasoning to such a level of detail that it can be /automated/, or performed automatically by a machine such as a computer. It reviews methods for commonsense reasoning and describes in detail a method for commonsense reasoning using the *event calculus*, which is based on classical predicate logic.

* TODO Comments

* TODO Topics

** What Is Commonsense Reasoning?

/Commonsense reasoning/ is a process that involves taking information about certain aspects of a scenario in the world and making inferences about other aspects of the scenario based on our /commonsense knowledge/, or knowledge of how the world works. Commonsense reasoning is essential to intelligent behavior and thought. It allows us to fill in the blanks, to reconstruct missing portions of a scenario, to figure out what happened, and to predict what might happen next. Commonsense reasoning stands in contrast to various types of expert reasoning such as economic, legal, mathematical, medical, and scientific reasoning.

** Key Issues of Commonsense Reasoning

Although commonsense reasoning comes naturally to us and appears to be simple, it is actually a complex process. In this section, we examine the previously mentioned examples of commonsense reasoning in detail. We introduce fundamental concepts and point out some of the key issues that must be addressed by any method for commonsense reasoning.

*** Representation

A /representation/ is something that resembles something else. For the purpose of automating commonsense reasoning, the representation should be a data structure or a sentence of a language defined by a formal syntax, and the representation should facilitate automated reasoning.

*** Objects, properties, events, and time

Several fundamental entities must be represented. First, we must represent objects in the world and agents such as persons and animals. Second, we must represent properties of the world that change over time. Third, we must represent events or actions that occur in the world. Fourth, we must represent time.

*** Object identity

We must represent the identities of objects.

*** Reasoning

Having formed a representation of a scenario, we can then perform commonsense /reasoning/ or /inference/. Because our goal is automation, the method of reasoning should be expressed as an algorithm or formal rule that takes representations as input and produces representations as output.

*** Representations of commonsense knowledge

We must construct representations of commonsense knowledge that can be used by the reasoning method to reason about a particular scenario.

*** Effects of events

We must be able to represent and reason about the effects of events on world properties. We must be able to reason from a specific event and general knowledge about the effects of events to the specific effects of the specific event.

*** Context-sensitive effects

We must be able to represent and reason about the context-sensitive effects of events. We should be able to represent that, if a person picks up a slippery object and is not careful, then the person will not be holding the object.

*** Nondeterministic effects

We must also be able to represent and reason about events with nondeterministic effects. We should be able to represent that, if a person picks up a slippery object, then the person may or may not be holding the object.

*** Concurrent events

We must be able to represent and reason about concurrent events. We should be able to represent that certain concurrent events are impossible; for example, a person cannot walk into two (2) rooms simultaneously. We must be able to reason about concurrent events with cumulative or canceling effects. For example, if a shopping cart is pushed, it moves forward. If it is pulled, it moves backwards. But, if it is simultaneously pulled and pushed, then it moves neither forward nor backward; instead, it spins around.

*** Space

In order to automate commonsense reasoning, we must be able to deal with space. We must represent the knowledge that, after a person walks into a room, the person will be in that room.

*** Indirect effects

We must be able to reason about the indirect effects or ramifications of events. For instance, we know that if a person is holding an object, then the object moves along with the person.

*** Preconditions

We must be able to represent and reason about the preconditions of actions or events. We need to represent two (2) preconditions of a person placing an object onto a surface:

  1. the person must be holding the object, and
  2. the person must be near the surface.

*** Commonsense law of inertia

This property of the commonsense world, that things tend to stay the same unless affected by some event, is known as the /commonsense law of inertia/.

*** Delayed effects and continuous change

We have so far seen that it is necessary for us to be able to represent and reason about the immediate effects of events, such as putting a topper in a drain and turning on the faucet. Thus, we should be able to infer that the stopper is in the drain, the faucet is running, and the sink is filling. In addition, we should be able to represent and reason about the delayed effects of events:

#+begin_quote
What will happen as a result? The water level will increase until it reaches the rim of the sink. Then the water will start spilling onto the floor.
#+end_quote

*** Release from the commonsense law of inertia

Recall that the commonsense law of inertia states that things stay the same unless affected by some event. But notice that the water level continues to change after the event of turning on the faucet. Therefore we must be able to represent that, after the faucet is turned on, the water level is released from the commonsense law of inertia and is permitted to vary. We must further represent that the water level is proportional to the time elapsed since the faucet was turned on.

*** Triggered events

In order to reason about this scenario, we must also be able to represent and reason about triggered events. The water level does not increase endlessly. When a sink is filling and the water reaches the rim of the sink, the sink will overflow. We should be able to represent and reason that, when a sink overflows, the water starts spilling onto the floow and the water level stops increasing. At this point, the water level will again be subject to the commonsense law of inertia.

*** Default reasoning

When we perform commonsense reasoning, we rarely have complete information. We are unlikely to know the state of affairs down to the last detail, everything about the events that are occurring, or everything about the way the world works. Therefore, when we perform commonsense reasoning, we must jump to conclusions. Yet, if new information becomes available that invalidates those conclusions, then we must also be able to take them back. Reasoning in which we reach conclusions and retract those conclusions (when warranted) is known as /default reasoning/.

*** Mental states

We must represent the piece of commonsense knowledge that, if an agent has an unsatisfied goal, then the agent will form a plan to achieve that goal. We must further represent that agents act on their plans.

*** Reasoning types

A method for automated commonsense reasoning must support several types of commonsense reasoning. The first is /temporal projection/ or /prediction/, in which we start with an initial state and some events and then reason about the state the results from the events. The second type of reasoning is /abduction/, in which we start with an initial state and a final state and then reason about the events that lead from the initial state to the final state. The third type of reasoning is /postdiction/, in which we start with some events that lead to a state and then reason about the state prior to the events.

*** SUMMARY

Any method for commonsense reasoning must address the following:

  - /Representation/. The method must represent scenarios in the world and must represent commonsense knowledge about the world.
  - /Commonsense entities/. The method must represent objects, agents, time-varying properties, events, and time.
  - /Commonsense domains/. The method must represent and reason about time, space, and mental states.
  - /Commonsense phenomena/. The method must address the commonsense law of inertia, release from the commonsense law of inertia, concurrent events with cumulative and canceling effects, context-sensitive effects, continuous change, delayed effects, indirect effects, nondeterministic effects, preconditions, and triggered events.
  - /Reasoning/. The method must specify processes for reasoning using representations of scenarios and representations of commonsense knowledge. The method must support default reasoning, temporal projection, abduction, and postdiction.

** The Event Calculus

The event calculus addresses all the key issues of commonsense reasoning described in the previous section. Using the event calculus we can represent commonsense knowledge, represent scenarios, and use the knowledge to reason about the scenarios.

*** Events, Fluents, and Timepoints

The basic notions of the event calculus are as follows:

  - an /event/ represents an event or action that may occur in the world, such as a person picking up a glass; we use the words /event/ and /action/ interchangeably
  - a /fluent/ represents a time-varying property of the world, such as the location of a physical object
  - a /timepoint/ represents an instant of time, such as 9:30 AM Greenwich Mean Time on November 13, 2017; the event calculus uses /linear time/, in which time is considered to be a line, rather than the /branching time/ of the situation calculus, in which time is considered to be a tree

An event may occur or happen at a timepoint. A fluent has a truth value at a timepoint or over a timepoint interval; the possible truth values are true and false. After an event occurs, the truth values of the fluents may change. We have commonsense knowledge about the effects of events on fluents. Specifically, we have knowledge about events that initiate fluents and events that terminate fluents.

For example, we know that the event of picking up a glass initiates the fluent of holding the glass and that the event of setting down a glass terminates the fluent of holding the glass. We represent these notions in first-order logic as follows:

   /HoldsAt(f,t)/ represents that fluent /f/ is true at timepoint /t/.
   /Happens(e,t)/ represents that event /e/ occurs at timepoint /t/.
   /Initiates(e,f,t)/ represents that, if event /e/ occurs at timepoint /t/, then fluent /f/ will be true after /t/.
   /Terminates(e,f,t)/ represents that, if event /e/ occurs at timepoint /t/, then fluent /f/ will be false after /t/.

**** A simple example

Here is a simple example of how the event calculus works. We use a simplified version of the event calculus, consisting of the following single axiom:

#+begin_center
(Happens(e, t_1) \wedge Initiates(e, f, t_1) \wedge t_1 < t_2 \wedge
\neg\exists e, t (Happens(e, t) \wedge t_1 < t \wedge t < t_2 \wedge Terminates(e, f, t))) \Rightarrow
HoldsAt(f, t_2)
#+end_center
